In [1]:
# Import the dependencies.

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Create a set of random latitude and longitude combinations.

lats = np.random.uniform(low=-90.000, high=90.000, size=50)
lngs = np.random.uniform(low=-180.000, high=180.000, size=50)
lat_lngs = zip(lats, lngs)
lat_lngs

In [3]:
coordinates = list(lat_lngs)

In [4]:
from citipy import citipy

In [5]:
# Create a list for holding the cities.
cities = []

# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
        
# Print the city count to confirm sufficient count.
len(cities)

45

In [6]:
import requests 
from config import weather_api_key

url = "http://api.openweathermap.org/data/2.5/weather?"

In [7]:
query_url = url + 'appid=' + weather_api_key + "&q=" + city

In [8]:
weather_response = requests.get(query_url)
weather_json = weather_response.json()

In [9]:
# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [10]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

Beginning Data Retrieval
-----------------------------

In [11]:
# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + 'appid=' + weather_api_key + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
# Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_descript = city_weather["weather"][0]["description"]
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Current Description": city_descript})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Processing Record 1 of Set 1 | sola
Processing Record 2 of Set 1 | rikitea
Processing Record 3 of Set 1 | nikolskoye
Processing Record 4 of Set 1 | michurinsk
Processing Record 5 of Set 1 | kapaa
Processing Record 6 of Set 1 | hilo
Processing Record 7 of Set 1 | castro
Processing Record 8 of Set 1 | rawson
Processing Record 9 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 10 of Set 1 | kropotkin
Processing Record 11 of Set 1 | atuona
Processing Record 12 of Set 1 | kaitangata
Processing Record 13 of Set 1 | hermanus
Processing Record 14 of Set 1 | miyako
Processing Record 15 of Set 1 | hobart
Processing Record 16 of Set 1 | sioux lookout
Processing Record 17 of Set 1 | san giovanni rotondo
Processing Record 18 of Set 1 | bluff
Processing Record 19 of Set 1 | puerto ayora
Processing Record 20 of Set 1 | ambon
Processing Record 21 of Set 1 | albany
Processing Record 22 of Set 1 | kahului
Processing Record 23 of Set 1 | tuktoyaktuk
Processing Record 24 of Set 1 | ambulu
Processing Record 25 of Set 1 | nanortalik
Processing Record 26 of Set 1 | barrow
Processing Record 27 of Set 1 | kalmunai
Processing Record 28 of Set 1 | saint andrews
Processing Record 29 of Set 1 | saleaula
City not found. Skipping...
Processing Record 30 of Set 1 | el retorno
Processing Record 31 of Set 1 | pevek
Processing Record 32 of Set 1 | mahajanga
Processing Record 33 of Set 1 | isangel
Processing Record 34 of Set 1 | talnakh
Processing Record 35 of Set 1 | santa cruz
Processing Record 36 of Set 1 | busselton
Processing Record 37 of Set 1 | carnarvon
Processing Record 38 of Set 1 | tuscaloosa
Processing Record 39 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 40 of Set 1 | cape town
Processing Record 41 of Set 1 | paamiut
Processing Record 42 of Set 1 | jujuy
City not found. Skipping...
Processing Record 43 of Set 1 | nizhneyansk
City not found. Skipping...
Processing Record 44 of Set 1 | butaritari
Processing Record 45 of Set 1 | saint-philippe
-----------------------------
Data Retrieval Complete
-----------------------------

In [12]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)

In [13]:
city_data_df["Max Temp"] = (((city_data_df["Max Temp"] - 273.15) * 9) / 5) + 32

In [14]:
city_data_df["Lat"] = city_data_df["Lat"].map("{:.2f}".format)
city_data_df["Lng"] = city_data_df["Lng"].map("{:.2f}".format)
city_data_df["Max Temp"] = city_data_df["Max Temp"].map("{:.2f}".format)

In [15]:
new_column_order = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description"]

city_data_df = city_data_df[new_column_order]

city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Sola,VU,-13.88,167.55,79.36,78,94,11.77,overcast clouds
1,Rikitea,PF,-23.12,-134.97,73.35,74,100,9.47,overcast clouds
2,Nikolskoye,RU,59.70,30.79,58.87,79,97,2.15,overcast clouds
3,Michurinsk,RU,52.90,40.49,62.17,93,100,5.09,light rain
4,Kapaa,US,22.08,-159.32,83.19,71,20,8.23,few clouds
5,Hilo,US,19.73,-155.09,90.28,69,0,5.14,clear sky
6,Castro,BR,-24.79,-50.01,46.40,96,100,2.36,overcast clouds
7,Rawson,AR,-43.30,-65.10,49.66,55,61,3.65,broken clouds
8,Kropotkin,RU,45.44,40.58,70.97,52,6,5.46,clear sky
9,Atuona,PF,-9.80,-139.03,77.50,72,0,9.88,clear sky
10,Kaitangata,NZ,-46.28,169.85,44.71,61,30,2.58,scattered clouds
11,Hermanus,ZA,-34.42,19.23,50.81,89,94,3.59,light rain
12,Miyako,JP,39.64,141.95,81.46,76,100,1.16,overcast clouds
13,Hobart,AU,-42.88,147.33,53.26,72,75,4.63,broken clouds
14,Sioux Lookout,CA,50.10,-91.92,56.37,67,0,1.81,clear sky
15,San Giovanni Rotondo,IT,41.70,15.72,67.62,78,0,4.63,clear sky
16,Bluff,NZ,-46.60,168.33,44.80,56,8,4.20,clear sky
17,Puerto Ayora,EC,-0.74,-90.35,69.55,93,93,2.68,overcast clouds
18,Ambon,ID,-3.70,128.18,86.14,70,40,1.54,scattered clouds
19,Albany,US,42.60,-73.97,67.89,84,13,1.57,few clouds
20,Kahului,US,20.89,-156.47,89.62,59,20,13.89,few clouds
21,Tuktoyaktuk,CA,69.45,-133.04,46.62,82,100,7.22,overcast clouds
22,Ambulu,ID,-8.35,113.61,82.24,72,36,1.17,scattered clouds
23,Nanortalik,GL,60.14,-45.24,44.67,98,100,3.77,moderate rain
24,Barrow,US,71.29,-156.79,46.42,93,100,6.69,light rain
25,Kalmunai,LK,7.42,81.82,80.74,64,97,1.66,overcast clouds
26,Saint Andrews,US,34.05,-81.13,84.29,60,40,2.06,scattered clouds
27,El Retorno,CO,2.33,-72.63,71.01,97,74,0.80,broken clouds
28,Pevek,RU,69.70,170.31,43.14,90,33,1.63,scattered clouds
29,Mahajanga,MG,-15.72,46.32,66.22,59,20,4.12,few clouds
30,Isangel,VU,-19.55,169.27,77.11,57,75,5.14,broken clouds
31,Talnakh,RU,69.49,88.40,49.21,60,72,4.75,broken clouds
32,Santa Cruz,BO,-17.80,-63.17,53.06,76,0,1.54,clear sky
33,Busselton,AU,-33.65,115.33,57.65,69,70,1.96,broken clouds
34,Carnarvon,AU,-24.87,113.63,62.17,40,0,8.32,clear sky
35,Tuscaloosa,US,33.21,-87.57,78.58,89,0,1.54,clear sky
36,Cape Town,ZA,-33.93,18.42,56.12,94,20,3.09,few clouds
37,Paamiut,GL,61.99,-49.67,43.50,93,100,5.18,light rain
38,Butaritari,KI,3.07,172.79,81.84,73,14,6.59,few clouds
39,Saint-Philippe,RE,-21.36,55.77,65.79,80,84,6.39,light rain

In [20]:
# Create the output file (CSV).
output_data_file = "Weather_Database.csv"

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")